name: 💻 CI

on:
    push:
        branches: [main]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v3

            - name: 📗 Setup NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/hydrogen"

            - name: 🔨 Build Project
              run: |
                  npm install
                  npm run build

            - name: 🧪 Test Project
              run: |
                  npm run test
