name: 💻 SonarCloud

on:
    push:
        branches: [dev]

jobs:
    sonarcloud:
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v3
              with:
                    fetch-depth: 0
              
            - name: 💻 SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
